name: Upgrade dependencies

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  upgrade_dependencies:
    name: Upgrade dependencies
    runs-on: ubuntu-latest
    if: github.repository_owner == 'sebastianczech'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Install trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy

      - name: Install terraform-docs
        run: |
          curl -sSLo /tmp/terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.19.0/terraform-docs-v0.19.0-linux-amd64.tar.gz
          tar -xzf /tmp/terraform-docs.tar.gz -C /tmp
          sudo mv /tmp/terraform-docs /usr/local/bin/

      - name: Install tflint
        run: |
          curl -sSLo /tmp/tflint.zip https://github.com/terraform-linters/tflint/releases/download/v0.55.1/tflint_linux_amd64.zip
          unzip /tmp/tflint.zip -d /tmp
          sudo mv /tmp/tflint /usr/local/bin/

      - name: Install terrascan
        run: |
          curl -L https://github.com/tenable/terrascan/releases/download/v1.19.9/terrascan_1.19.9_Linux_x86_64.tar.gz -o /tmp/terrascan.tar.gz
          tar -xzf /tmp/terrascan.tar.gz -C /tmp terrascan
          sudo mv /tmp/terrascan /usr/local/bin/
          terrascan init

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.3"

      - name: Run pre-commit
        id: precommit
        run: pre-commit run --all-files

      - name: Create Pull Request
        if: ${{ failure() && steps.precommit.conclusion == 'failure' }}
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: Upgrade dependencies"
          title: "chore: Upgrade dependencies"
          body: "This PR upgrades dependencies."
          branch: upgrade-dependencies
          base: main
          labels: dependencies
          assignees: sebastianczech
          reviewers: sebastianczech
          draft: always-true
